services:
  mysql:
    container_name: 'mysql-restdb'
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=mysql-restdb'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=user'
      - 'MYSQL_ROOT_HOST=%'
    ports:
      - '3306:3306'